/* Generated by web/tools/build_example_data.py — do not edit by hand. */
window.PATENTCLAW_EXAMPLE = {
 "meta": {
  "generator_job_id": "l2d-e379985a160a",
  "review_job_id": "review-7ee0e15fda17",
  "input_name": "NIPS26_multi_cot_wzy.zip",
  "model": "gpt-5.5",
  "offline_mode": false,
  "agent_sequence": [
   "paper_understanding_agent",
   "invention_mining_agent",
   "technical_solution_agent",
   "embodiment_evidence_agent",
   "technical_disclosure_writer_agent"
  ],
  "review_mode": "online",
  "policy_id": "cn-invention-disclosure-2026.1",
  "checklist_version": "cn-invention-checklist/1.0",
  "max_revision_rounds": 3,
  "revision_rounds": 3,
  "revision_termination_reason": "max_rounds_reached",
  "generator_created_at": "2026-08-13T07:13:00.984859Z",
  "generator_updated_at": "2026-08-13T07:18:37.858418Z",
  "generator_seconds": 336
 },
 "source": {
  "title": "Can Linguistic Reasoning Vectors Enhance Multimodal Reasoning Ability?",
  "abstract": "Most Vision-Language Models (VLMs) are built by extending pretrained Large Language Models (LLMs) with visual modules and multimodal alignment. However, this multimodal scaling often degrades the language-side reasoning ability originally encoded in the base LLM. While the base LLM retains usable reasoning after scaling, the aligned VLM itself cannot reliably access this ability. Therefore, recovering the degraded reasoning capability in VLMs would benefit more from seeking help from the base LLM than from the VLM alone.\nMotivated by this, we propose LIFT (Language-side reasoning Facilitation and Transfer), a lightweight vector-intervention method \n\nthat transfers reasoning capability from the base LLM to the VLM without retraining the backbone. \nLIFT defines Reasoning Vectors as answer-token hidden-state differences between a Reasoner path with an explicit reasoning trace and a Solver path without it, and injects these vectors into language-side activations of the target VLM. LIFT further supports learnable vector adaptation while keeping the VLM backbone frozen. \nWe evaluate LIFT on two VLMs across six reasoning benchmarks, comparing Reasoning Vectors extracted from the base LLM and from the aligned VLM under matched protocols.\n\nResults show that LLM-derived vectors consistently outperform VLM-derived vectors, confirming that the base LLM is a more effective source for recovering reasoning. LIFT partially recovers degraded reasoning through lightweight language-side interventions.\nFurther analyses show that Reasoning Vectors influence intermediate reasoning behavior rather than merely altering final answers.",
  "root_file": "neurips_2026.tex",
  "section_titles": [
   "Introduction",
   "Related Work",
   "Methodology",
   "Reasoning Vector Formulation",
   "Reasoning Vector Sources and Extraction",
   "Learnable Vector Adaptation",
   "Layer Selection and Injection",
   "Experiments",
   "Setup and Implementation Details",
   "Reasoning Vectors Transfer Effectively Across Modalities",
   "LLM-derived Vectors Provide More Reliable Interventions than VLM-derived Vectors",
   "LLM-derived Vectors Outperform VLM-MM Vectors",
   "Meaningful Initialization Matters for Learnable Vector Adaptation",
   "Representation Alignment and Layer-wise Analysis",
   "Conclusion and Limitations",
   "Derivation of Reasoning Vector",
   "Datasets and Evaluation Protocols",
   "Prompting and Generation Settings",
   "Support Set Construction and Vector Extraction",
   "Reproducibility Details",
   "Statistical Uncertainty of Main Accuracy Differences",
   "Additional-seed Robustness Check",
   "Same-norm Random-vector Control",
   "Additional Attention-level Injection Results",
   "Additional Case Studies with Full Reasoning Traces",
   "NeurIPS Paper Checklist"
  ],
  "counts": {
   "source_files": 8,
   "sections": 26,
   "equations": 12,
   "tables": 12,
   "algorithms": 0,
   "figures": 5,
   "evidence": 1008
  },
  "figures": [
   {
    "label": "fig:intro_lift",
    "caption": "Motivation of LIFT. Multimodal alignment may change language-side reasoning directions in the VLM. LIFT tests whether Reasoning Vectors from the base LLM can be reused as lightweight interventions in the aligned VLM.",
    "asset_file": "intro.pdf"
   },
   {
    "label": "fig:method",
    "caption": "Overview of LIFT. (a) For each layer, LIFT computes hidden-state differences between the Reasoner and Solver paths and averages these differences to obtain the Reasoning Vector. (b) Learnable adaptation optimizes only the injected vector parameters while keeping the VLM backbone frozen. (c) At inference, vectors are injected into selected VLM layers.",
    "asset_file": "method.pdf"
   },
   {
    "label": "fig:case",
    "caption": "Representative Case Studies of Reasoning Repairs.",
    "asset_file": "case_study.pdf"
   },
   {
    "label": "fig:cos",
    "caption": "Cross-layer cosine similarity between LLM- and VLM-derived vectors on GSM8K.",
    "asset_file": "cos.pdf"
   },
   {
    "label": "fig:layerwise",
    "caption": "Layer-wise performance of LLM- and VLM-derived vectors averaged over six datasets.",
    "asset_file": "layerwise.pdf"
   }
  ]
 },
 "disclosure": {
  "invention_title": "语言侧推理向量提取及视觉语言模型干预方法和系统",
  "technical_field": "本发明涉及人工智能与多模态信息处理技术领域，具体涉及一种从基础语言模型或视觉语言模型中提取语言侧推理向量，并在冻结视觉语言模型骨干参数的情况下，通过隐藏状态或注意力头输出的加法式干预改善文本及图文推理处理的方法、系统和存储介质。",
  "background": [
   "视觉语言模型通常包括视觉编码器、跨模态投影模块和由预训练大语言模型形成的语言骨干，并通过多模态指令调优实现视觉信息与语言信息的对齐。",
   "基础语言模型在多模态扩展前已具备一定的语言推理能力。论文材料记载，经过多模态扩展后，对应视觉语言模型在纯文本推理或多步推理过程中存在中间变量改变、条件遗漏、数值复制错误或输出目标偏离等失败情形。",
   "现有视觉语言模型推理增强方案包括思维链监督、包含推理依据的指令调优、验证式推理、树搜索、奖励引导解码、强化学习和其他后训练方法。上述方案通常直接训练目标视觉语言模型或改变其推理解码过程。",
   "激活向量技术能够通过不同上下文下内部激活的差异形成行为干预方向，并通过加法方式作用于模型隐藏状态。现有研究未充分解决如何将多模态对齐前基础语言模型中的推理相关激活差异迁移至其对应视觉语言模型。"
  ],
  "prior_art_defects": [
   "直接对目标视觉语言模型实施指令调优、强化学习或其他后训练通常需要更新大量模型参数，并需要相应训练数据及计算资源。",
   "仅从多模态对齐后的视觉语言模型提取语言侧干预方向时，所提取方向会混入多模态对齐后的语言侧表征状态；在论文所测试的模型和数据集上，该来源的平均干预效果低于对应基础语言模型来源。",
   "问题、推理轨迹和答案形成的序列长度不同，若直接比较完整序列的隐藏状态，问题标记和推理轨迹标记之间缺少稳定的一一对应关系。",
   "激活干预对注入层敏感；在论文逐层评测配置下，不同语言层的干预效果存在波动，因此需要通过留出开发子集确定注入层。",
   "语言侧激活干预不能直接修正由视觉感知错误或视觉定位错误造成的输出问题。"
  ],
  "technical_problem": [
   "如何在不更新目标视觉语言模型骨干和视觉编码器参数的情况下，提取并复用基础语言模型中的推理相关内部表征。",
   "如何在包含推理轨迹和不包含推理轨迹的不同长度输入之间，获得位置可对齐且可跨样本聚合的推理表征。",
   "如何将任务级推理表征迁移至对应视觉语言模型，并在不向评测提示附加支持样本的情况下作用于自回归生成过程。",
   "如何根据目标模型和目标任务选择适于激活干预的语言层，并可选地对提取向量进行轻量适配。"
  ],
  "overall_solution": "获取由问题Q、推理轨迹T和最终答案A构成的支持样本，并针对同一向量来源模型分别构造推理路径C_R=(Q,T,A)和求解路径C_S=(Q,A)，执行教师强制前向计算。仅读取两条路径中最终答案区间内相互对齐的答案标记在各语言层的隐藏状态，计算推理路径隐藏状态与求解路径隐藏状态之差，再依次对答案标记和支持样本求平均，得到逐层任务级推理向量。利用独立开发子集逐层评测并确定目标视觉语言模型的注入层，在目标模型自回归生成时将对应推理向量或由其初始化并优化的可学习向量加到所选语言层的语言标记激活中。目标视觉语言模型骨干和视觉编码器保持冻结，支持样本不加入评测提示。",
  "detailed_steps": [
   "S101，确定目标视觉语言模型及与其对应的基础语言模型，并获取支持样本。每个支持样本包括问题Q、由向量来源模型生成的推理轨迹T以及最终答案A",
   "S102，按照向量来源模型的回答正确性筛选支持样本，仅保留由当前向量来源模型正确回答的样本。基础语言模型来源和视觉语言模型来源可形成不同的正确样本子集。",
   "S103，针对每个筛选后的支持样本，使用同一向量来源模型执行两个教师强制前向路径：推理路径接收C_R=(Q,T,A)，求解路径接收C_S=(Q,A)。",
   "S104，在每一语言层l中，仅读取两条路径最终答案区间内相互对齐的答案标记a的隐藏状态h_l(a;C_R)和h_l(a;C_S)，不将问题标记或推理轨迹标记作为差分位置。",
   "S105，计算答案标记级隐藏状态差δ_l(a)=h_l(a;C_R)-h_l(a;C_S)，该差值表示加入推理轨迹后答案标记表征产生的变化近似。",
   "S106，对第i个样本的答案标记级差值在答案区间A_i内求平均，再对N个筛选后的支持样本求平均，得到第l层任务级推理向量r_l=(1/N)Σ_i[(1/|A_i|)Σ_{a∈A_i}(h_l(a;C_R,i)-h_l(a;C_S,i))]，并形成逐层向量集合R={r_l}。",
   "S107，从训练数据随机抽取100个样本形成留出开发子集。针对每个候选语言层分别注入对应推理向量并评测开发子集性能，将开发子集性能最佳的层确定为最终注入层。不同向量来源和适配设置采用相同的选层协议，最终评测样本不参与选层。",
   "S108，在静态迁移方式下，将所选层对应的r_l作为注入向量，并按照x̃_l=x_l+μr_l进行加法式干预；论文主实验中的静态干预强度μ固定为1.0。",
   "S109，在可学习适配方式下，以基础语言模型来源或视觉语言模型来源的推理向量初始化θ_l，按照x̃_l=x_l+θ_l实施注入，仅优化注入向量参数，冻结目标视觉语言模型骨干和视觉编码器。",
   "S110，可学习适配采用对齐损失，不采用语言模型交叉熵损失。论文给出的损失形式为L_rec=||z_l^R-z_l^S||_2^2以及L=λ_rec L_rec；已披露训练配置包括AdamW优化器、学习率1×10^-4、批量大小1、梯度累积4步、训练6个epoch、权重衰减1×10^-3、warmup比例0.1、最大梯度范数1.0和16位混合精度。",
   "S111，在目标视觉语言模型推理过程中，将静态推理向量或可学习向量注入所选语言层的语言侧激活，不修改视觉编码器。支持样本及其推理轨迹不作为上下文示例附加到评测提示。",
   "S112，采用与未干预基线相同的zero-shot思维链提示、解码配置、评测划分和答案解析器生成结果，并根据任务类型解析数值答案、选择项或是非答案。",
   "S113，输出生成答案及可选的推理轨迹，并计算逐数据集准确率及多个基准的算术平均准确率。"
  ],
  "key_innovations": [
   "针对同一问题和最终答案构造包含推理轨迹与不包含推理轨迹的成对教师强制前向路径，以提取推理轨迹引起的内部表征变化。",
   "仅在两条路径共有且可对齐的最终答案标记位置计算隐藏状态差，避免对不同长度推理轨迹进行全序列强制对齐。",
   "将答案标记级差值依次按答案区间和支持样本聚合，形成与语言层对应的任务级推理向量集合。",
   "从目标视觉语言模型对应的基础语言模型提取推理向量，并将该向量迁移至目标视觉语言模型的语言骨干。",
   "通过留出开发子集逐层确定注入位置，并在冻结目标视觉语言模型骨干及视觉编码器的条件下实施静态注入或可学习向量适配。",
   "利用文本推理支持集形成语言侧推理向量，并将其用于图文推理任务，不要求将支持样本作为上下文示例输入目标模型。"
  ],
  "beneficial_effects": [
   "在论文披露的Qwen2.5-VL-7B-Instruct、InternVL2.5-8B及六个推理基准配置下，基础语言模型来源的静态推理向量将六基准平均准确率分别由66.6%提高至68.3%、由67.8%提高至69.0%。",
   "在相同实验配置下，基础语言模型来源静态向量的平均准确率高于视觉语言模型来源静态向量；后者在两个目标模型上的平均准确率分别为67.5%和68.3%。",
   "在MathVista、MathVision和ScienceQA的已披露配置下，从文本支持集提取的基础语言模型来源向量能够用于图文推理任务。Qwen2.5-VL在MathVista和MathVision上分别由68.5%和25.0%提高至69.1%和26.6%，InternVL2.5分别由62.8%和22.7%提高至64.0%和25.0%。",
   "在论文披露的可学习适配配置下，以基础语言模型来源向量初始化后，Qwen2.5-VL和InternVL2.5的六基准平均准确率分别达到69.1%和69.4%，高于对应静态向量的68.3%和69.0%。",
   "同范数随机向量对照在Qwen2.5-VL和InternVL2.5上的平均准确率分别为66.4%和66.1%，未复现基础语言模型来源向量的增益，表明在所测配置下观察到的效果不能仅由扰动范数解释。",
   "上述效果仅限于论文披露的模型、支持集、基准、层选择方法和解码配置，不构成对其他模型架构、任务或部署场景的无条件性能保证。"
  ],
  "embodiments": [
   "实施例一：采用Qwen2.5-7B-Instruct作为向量来源模型，采用Qwen2.5-VL-7B-Instruct作为目标视觉语言模型。按照Reasoner-Solver双路径协议提取逐层任务级推理向量，在100个训练样本形成的开发子集上选择注入层，并以μ=1.0实施静态语言侧隐藏状态注入。",
   "实施例二：采用InternLM2.5-7B-Chat作为向量来源模型，采用InternVL2.5-8B作为目标视觉语言模型，其余提取、聚合、选层和静态注入流程与实施例一相同。",
   "实施例三：比较三类向量来源，包括基础语言模型结合文本支持集形成的LLM-derived向量、目标视觉语言模型结合文本支持集形成的VLM-derived向量，以及目标视觉语言模型结合多模态支持集形成的VLM-MM向量。三类来源均执行相同的双路径提取协议。",
   "实施例四：对LLM-derived或VLM-derived向量执行可学习适配。仅训练注入向量，使用对齐损失，冻结目标视觉语言模型骨干和视觉编码器，并采用论文披露的AdamW及相关超参数。",
   "实施例五：执行跨模态支持源复用。GSM8K、MathVista和MathVision使用GSM8K支持集；CommonsenseQA和StrategyQA使用各自训练划分；ScienceQA使用CommonsenseQA支持集。文本支持集形成的向量用于对应图文任务时仍注入语言骨干。",
   "实施例六：采用注意力头输出级注入。对层l的注意力头m，计算v_Attn^(l,m)=(1/N)Σ_i[(1/|A_i|)Σ_{a∈A_i}(o_R,i^(l,m)(a)-o_S,i^(l,m)(a))]，并按照õ^(l,m)(t)=o^(l,m)(t)+μv_Attn^(l,m)在生成语言标记位置实施干预；论文披露该实施例的μ为1.0。"
  ],
  "experimental_evidence": [
   "评测模型为Qwen2.5-VL-7B-Instruct和InternVL2.5-8B，对应基础语言模型分别为Qwen2.5-7B-Instruct和InternLM2.5-7B-Chat。",
   "评测数据包括GSM8K 1319个样本、MathVista testmini 1000个样本、MathVision 304个样本、CommonsenseQA 1221个样本、StrategyQA 687个样本和ScienceQA 4241个样本。",
   "所有基线和干预方法使用相同的zero-shot思维链提示、确定性解码、beam size为1且关闭采样。文本基准的最大新生成标记数为512，多模态基准为4096；随机种子为42，另有说明的附加种子实验除外。",
   "主实验中，Qwen2.5-VL的Baseline、LLM-derived、VLM-derived、LLM-learnable和VLM-learnable平均准确率依次为66.6%、68.3%、67.5%、69.1%和67.2%。",
   "主实验中，InternVL2.5的Baseline、LLM-derived、VLM-derived、LLM-learnable和VLM-learnable平均准确率依次为67.8%、69.0%、68.3%、69.4%和66.6%。",
   "在MathVision和ScienceQA两项平均结果上，Qwen2.5-VL的LLM-derived、VLM-MM和VLM-derived分别为57.4%、57.0%和56.8%；InternVL2.5分别为60.9%、60.6%和60.1%。",
   "配对bootstrap分析使用相同评测划分中的逐样本正确性对并执行10000次重采样。LLM-derived相对Baseline的宏平均差值为+1.45个百分点，95%置信区间为[0.45,2.45]；VLM-derived相对Baseline为+0.70个百分点，区间为[0.12,1.28]；LLM-derived相对VLM-derived为+0.75个百分点，区间为[0.15,1.35]。",
   "附加随机种子实验保持评测划分不变并重新采样支持集及选层开发样本，两个目标模型上仍观察到LLM-derived高于Baseline和VLM-derived的趋势。",
   "注意力头输出级注入中，Qwen2.5-VL的Baseline、LLM-derived和VLM-derived平均准确率分别为66.6%、67.5%和67.3%；InternVL2.5分别为67.8%、69.1%和68.8%。",
   "论文报告的案例显示，部分样本中的干预改变了重复情况枚举、端到端齿轮关系、区域计数、剩余周数、线性价格增长条件、复合属性判断和变化率符号等中间推理过程。该案例证据属于定性观察，不代表所有输入均获得修正。",
   "实验通过PyTorch实现；静态评测使用torch.float16，可学习适配使用16位混合精度；硬件包括单张24GB NVIDIA RTX 3090或48GB NVIDIA RTX A6000。"
  ],
  "drawing_descriptions": [
   "图1为LIFT动机示意图，示出多模态对齐会改变视觉语言模型中的语言侧推理方向，以及来自基础语言模型的推理向量可作为对齐后视觉语言模型中的轻量干预方向。",
   "图2为LIFT方法概览图，示出各层中Reasoner路径与Solver路径的隐藏状态差分及平均以获得Reasoning Vector、可学习适配仅优化注入向量并冻结视觉语言模型骨干，以及推理时向选定视觉语言模型层注入向量。",
   "图3为代表性推理修复案例图。",
   "图4为GSM8K上基础语言模型来源向量与视觉语言模型来源向量的跨层余弦相似度图。",
   "图5为基础语言模型来源向量与视觉语言模型来源向量在六个数据集上平均的逐层性能图。"
  ],
  "terminology": [
   "基础语言模型（LLM）：在多模态扩展前使用的语言模型；已验证实例为Qwen2.5-7B-Instruct和InternLM2.5-7B-Chat。",
   "视觉语言模型（VLM）：包括视觉编码器和语言骨干并能够处理图文输入的模型；已验证实例为Qwen2.5-VL-7B-Instruct和InternVL2.5-8B。",
   "推理路径（Reasoner path）：输入上下文为C_R=(Q,T,A)的教师强制前向路径。",
   "求解路径（Solver path）：输入上下文为C_S=(Q,A)的教师强制前向路径。",
   "推理向量：推理路径与求解路径在对齐答案标记处的语言侧隐藏状态差经答案标记和支持样本聚合后得到的任务级向量。",
   "h_l(a;C)：上下文C下，答案标记a在语言层l的隐藏状态，其最后一维与该层语言隐藏维度一致。",
   "δ_l(a)：第l层答案标记级差向量，定义为h_l(a;C_R)-h_l(a;C_S)。",
   "r_l：第l层任务级静态推理向量，由多个支持样本的答案标记级差向量平均获得。",
   "R={r_l}：覆盖各语言层的任务级推理向量集合。",
   "x_l与x̃_l：分别表示目标视觉语言模型所选语言层的原始激活和加法干预后的激活。",
   "θ_l：可学习注入向量，其维度与所注入语言层的激活维度匹配。",
   "LLM-derived：从对应基础语言模型及文本支持集提取的推理向量。",
   "VLM-derived：从目标视觉语言模型语言骨干及文本支持集提取的推理向量。",
   "VLM-MM：从目标视觉语言模型及多模态支持集提取、但仍在语言侧答案表征上计算的推理向量。",
   "语言侧：推理向量的提取和注入位置位于语言骨干，而非视觉编码器。"
  ],
  "system_implementation": [
   "支持样本管理模块接收问题、推理轨迹、最终答案及正确性标签，并按照向量来源模型的回答正确性产生筛选后的支持样本集。",
   "双路径前向模块调用向量来源模型，对同一支持样本分别执行C_R和C_S的教师强制前向计算。",
   "答案标记对齐模块确定两条路径的最终答案区间，并输出相互对应的答案标记位置。",
   "激活采集模块从模型各语言层读取对齐答案标记的隐藏状态，或在替代实施方式中读取注意力头输出。",
   "向量计算模块执行隐藏状态相减以及答案标记维度和样本维度的平均，生成逐层推理向量对象。",
   "选层模块将逐层推理向量与目标视觉语言模型的候选层关联，在100个训练样本组成的开发子集上计算性能并输出选定层标识。",
   "适配模块可选地加载静态推理向量作为θ_l初始值，冻结目标模型参数并根据对齐损失更新θ_l。",
   "运行时注入模块在目标模型前向执行期间捕获选定语言层的激活，并返回原激活与注入向量之和。",
   "生成模块接收文本输入或图文输入，调用目标视觉语言模型执行自回归生成，并将生成文本交给答案解析模块。",
   "评测模块根据数值、选择题或是非题解析规则生成逐样本正确性记录，并汇总准确率和跨基准算术平均值。"
  ],
  "data_and_interfaces": [
   "支持样本用于提供问题Q、推理轨迹T和最终答案A，并按照向量来源模型的回答正确性进行筛选；多模态支持样本可包含图像输入作为上下文，但推理向量仍从语言侧答案表征计算。",
   "路径输入接口接收token化后的C_R或C_S及教师强制标签，返回逐层隐藏状态；替代接口还可返回逐层逐头注意力输出。",
   "答案区间对象包括答案起始位置、结束位置及两条路径之间的对齐答案标记索引。具体程序化识别和异常对齐规则需由发明人确认。",
   "推理向量相关数据用于记录逐语言层得到的任务级推理向量r_l及其层对应关系，并可结合向量来源和支持集来源区分LLM-derived、VLM-derived或VLM-MM等来源设置。",
   "选层结果用于记录在留出开发子集上逐候选语言层评测后确定的选定注入层；不同向量来源和适配设置采用相同选层协议。",
   "模型注入接口接收目标层标识、注入向量和干预强度，并在模型处理器执行目标层前向计算时完成张量加法。",
   "可学习适配接口接收初始向量、离线支持集和训练配置，输出优化后的注入向量；目标模型权重和视觉编码器权重保持只读。",
   "生成接口接收文本标记以及可选视觉张量，返回生成标记序列、解析答案和可选推理轨迹。",
   "评测数据用于记录生成结果、解析答案和逐样本正确性，并在相同评测划分下基于逐样本正确性对执行配对bootstrap分析；评测过程采用论文披露的相同提示、解码配置、答案解析器和随机种子设置。",
   "处理器可通过模型前向钩子或等效模块接口读取和修改激活；具体挂接位置应与所实现模型结构一致，并由发明人进一步确认。"
  ],
  "implementation_boundaries": [
   "所述实验验证范围限于Qwen2.5-VL-7B-Instruct、InternVL2.5-8B及论文列明的六个推理基准，尚不能据此推定适用于任意视觉语言模型。",
   "本方法要求获得支持样本并执行离线双路径前向计算；推理向量的有效性受支持样本质量、正确样本数量和注入层选择影响。",
   "本方法在语言骨干而非视觉编码器中实施干预，不能直接保证修复视觉感知或视觉定位错误。",
   "论文未给出跨隐藏维度、跨层数或非对应模型之间的向量投影实现，因此不将任意异构模型间迁移作为已实施方案。",
   "主隐藏状态注入在推理阶段的自回归解码过程中，于所选语言模型层实施加法式干预；该过程仅修改语言 token 隐藏状态，不更新 VLM 参数，且支持样本及其提取轨迹不作为评测提示中的上下文示例。",
   "可学习适配损失中的λ_rec数值、z_l^R与z_l^S的精确定义及停止条件未完整披露。",
   "未披露各基准最终选定的具体层编号、候选层范围、性能并列处理规则以及跨任务共用层的验证结果。",
   "案例研究仅说明所展示样本中的中间推理变化，不构成所有错误类型均可被修复的技术保证。",
   "平均准确率提升是特定评测配置下的观察结果，不构成对实际部署输入、其他解码设置或其他数据分布的性能承诺。"
  ],
  "alternatives": [
   "静态隐藏状态注入方案：直接将任务级推理向量以强度1.0加到选定语言层，不执行向量训练。",
   "可学习向量适配方案：以LLM-derived或VLM-derived向量初始化θ_l，仅优化注入向量并冻结目标模型骨干和视觉编码器。",
   "向量来源替代方案：采用基础语言模型文本来源、目标视觉语言模型文本来源或目标视觉语言模型多模态来源；三种来源均已在论文中披露并比较。",
   "注意力头输出级注入方案：从Reasoner和Solver路径的注意力头输出差提取头级向量，并在对应头输出处进行加法式注入；该方案已在两个目标视觉语言模型上评测。",
   "跨模态支持源复用方案：MathVista和MathVision使用GSM8K文本支持集，ScienceQA使用CommonsenseQA文本支持集。"
  ],
  "inventor_confirmation_items": [
   "请确认主隐藏状态注入在Transformer块中的精确挂接点，是块输入、注意力残差后、MLP残差后还是块输出。",
   "请确认主隐藏状态注入覆盖的自回归时间步和标记范围，包括是否作用于提示预填充阶段、首个生成标记以及全部后续语言标记。",
   "请提供答案区间的程序化识别规则、多标记答案的对齐算法、特殊标记处理方式以及两条路径分词不一致时的处理规则。",
   "请确认筛选后支持样本数量N不足时的补采样、下限阈值或终止条件，并说明该支持样本规模设置是否在全部实施例中一致。",
   "请确认可学习适配中z_l^R和z_l^S的完整定义、λ_rec的具体数值、损失计算位置及训练停止条件。",
   "请提供各基准的候选层范围、最终选定层编号、选层性能指标及并列层处理规则。",
   "请确认基础语言模型和目标视觉语言模型必须满足的对应关系，包括分词器、层数及隐藏维度要求；如允许不一致，请提供层映射和维度投影实现。",
   "请确认注意力级注入针对全部注意力头还是选定注意力头，并明确其在注意力模块内部的具体挂接位置。",
   "请确认静态干预强度除1.0外是否执行过搜索或自适应设置；如已执行，请提供搜索范围、选择数据及对应结果。",
   "请确认是否存在与视觉侧特征联合干预的实际实现和验证；在获得相应证据前，该方案不作为已实施实施例。"
  ]
 },
 "review": {
  "legal_baseline": "中国发明专利技术交底书审查基线（基于专利法第二十六条、实施细则及专利审查指南；非法律意见）",
  "limitations": [
   "本工具审查对象是技术交底书，不替代权利要求撰写、专利性检索或法律意见。",
   "规则检查只能识别可形式化风险；创造性、保护范围和等同侵权判断须人工完成。"
  ],
  "human_review_checklist": [
   "确认申请主体、发明人及公开时间等程序性信息",
   "确认拟保护主题及必要技术特征，最终权利要求由专利代理师审核",
   "确认新增实施方式、参数范围和技术效果均有原始材料支持",
   "在提交前按国家知识产权局现行表格和电子申请格式进行终检"
  ],
  "initial": {
   "score": 32,
   "passed": false,
   "counts": {
    "pass": 22,
    "fail": 4,
    "needs_human_review": 4
   },
   "findings": [
    {
     "finding_id": "C-EV-02",
     "check_id": "EV-02",
     "dimension": "证据可追溯性",
     "severity": "major",
     "target_section": "S101",
     "target_path": "detailed_steps",
     "issue": "主要实验准确率、评测样本量、bootstrap统计量、随机向量对照、注意力级注入结果和可学习适配超参数均有表格或正文证据支持；但“每个支持来源采样500个样本”在当前证据列表中未见直接证据编号，属于数值参数不可逐项追溯。",
     "risk": "参数、样本量、实验结果、比较结论和统计量应有直接证据。",
     "suggested_revision": "删除“论文披露通常针对每个支持来源采样500个样本”，或补充原论文中支持该采样数量的直接证据编号；若仅为实施建议，改为“支持样本数量可根据任务和正确样本数量设置，并记录聚合样本数N”。",
     "evidence_ids": [
      "E0924",
      "E0925",
      "E0926",
      "E0929",
      "E0931",
      "E0932",
      "E0933",
      "E0934",
      "E0936",
      "E0937",
      "E0139",
      "E0360",
      "E0362",
      "E0363"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.78,
     "source": "llm"
    },
    {
     "finding_id": "F-TITLE_LONG",
     "check_id": "CF-02",
     "dimension": "完整性与形式",
     "severity": "minor",
     "target_section": "发明名称",
     "target_path": "invention_title",
     "issue": "发明名称为35字，超过常规25字控制值",
     "risk": "名称可能不够简明。",
     "suggested_revision": "压缩非必要修饰语，同时保留主题和技术类型。",
     "evidence_ids": [],
     "auto_fixable": false,
     "requires_inventor_confirmation": false,
     "confidence": 1.0,
     "source": "rule"
    },
    {
     "finding_id": "F-KNOWN_TECHNICAL_GAPS",
     "check_id": "EN-03",
     "dimension": "充分公开",
     "severity": "major",
     "target_section": "实现边界与发明人确认",
     "target_path": "inventor_confirmation_items",
     "issue": "Generator已识别出19项原始材料未充分披露的技术细节",
     "risk": "若这些细节属于实现发明不可缺少的条件，当前材料可能无法满足充分公开或权利要求支持要求。",
     "suggested_revision": "逐项向发明人确认并补充证据；当前重点包括：未见直接证据支持目标VLM与基础LLM层数或隐藏维度不一致时的层映射、投影矩阵或维度对齐策略；不得写成确定实施步骤。；未见直接证据支持不同tokenizer之间的答案token对齐或重分词策略；不得写成确定实施步骤。；未见直接证据支持静态隐藏状态注入是否作用于所有语言token、仅生成token、仅答案token或特定位置；除“language-token hidden states/selected language-model layer”外不应细化。；未见直接证据支持多层同时注入规则；论文主流程为选择层注入，注意力实验也按选层评测。；另有15项",
     "evidence_ids": [],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 1.0,
     "source": "rule"
    },
    {
     "finding_id": "C-EN-04",
     "check_id": "EN-04",
     "dimension": "充分公开",
     "severity": "major",
     "target_section": "data_and_interfaces / implementation_boundaries",
     "target_path": "data_and_interfaces",
     "issue": "核心向量计算公式、输入、聚合和注入形式已有披露，但可重复实施仍受关键缺口影响：答案区间/多标记答案对齐和异常分词处理规则未确定；主隐藏状态注入的精确挂接点和作用时间步未限定；可学习适配中z_l^R、z_l^S、λ_rec及停止条件未完整披露。这些缺口会影响本领域人员复现实验和实施系统。",
     "risk": "算法输入、计算规则、关键条件、输出和异常处理应足以让本领域人员实现。",
     "suggested_revision": "补充可执行规则：1）final_answer在C_R和C_S中的起止定位、token级对齐、特殊标记和分词不一致处理；2）隐藏状态注入在Transformer块中的具体hook位置及覆盖prefill/首token/后续token的范围；3）z_l^R、z_l^S的张量来源、λ_rec数值、损失计算层和停止条件。",
     "evidence_ids": [
      "E0073",
      "E0074",
      "E0075",
      "E0081",
      "E0097",
      "E0118",
      "E0122",
      "E0912",
      "E0913",
      "E0915"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.9,
     "source": "llm"
    },
    {
     "finding_id": "C-CS-03",
     "check_id": "CS-03",
     "dimension": "保护范围支撑",
     "severity": "major",
     "target_section": "invention_title",
     "target_path": "invention_title",
     "issue": "方法主题有较充分实施方式和实验支撑；系统主题可由支持样本管理、双路径前向、激活采集、向量计算、选层、适配、注入和评测模块支撑。但“存储介质”作为保护主题仅在标题出现，交底书未明确其承载的程序指令、处理器执行流程或与方法步骤的对应关系；上位概括到任意视觉语言模型也已通过边界限制，但仍需在权利要求撰写时避免超出两类已验证模型和对应模型关系。",
     "risk": "方法、系统、介质及上位概括均应由实施方式和证据支持。",
     "suggested_revision": "在system_implementation或新增对应顶层内容中补充“存储介质存储有程序指令，所述指令被处理器执行时实现S101-S113及可选注意力级注入步骤”；并在保护范围中限定为具有对应语言骨干维度/层映射条件的目标模型，避免概括到未披露的任意异构模型迁移。",
     "evidence_ids": [
      "E0063",
      "E0066",
      "E0093",
      "E0095",
      "E0122",
      "E0257",
      "E0259"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.76,
     "source": "llm"
    },
    {
     "finding_id": "F-AMBIGUOUS_BACKGROUND",
     "check_id": "WR-03",
     "dimension": "专利文体",
     "severity": "minor",
     "target_section": "background",
     "target_path": "background",
     "issue": "存在可能导致边界不清的相对或不确定用语：可能",
     "risk": "若无测量方法、参照对象或范围限定，技术特征可能不清楚。",
     "suggested_revision": "在原始材料支持范围内补充参照对象、计算方式、阈值或数值范围。",
     "evidence_ids": [],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 1.0,
     "source": "rule"
    },
    {
     "finding_id": "F-AMBIGUOUS_PRIOR_ART_DEFECTS",
     "check_id": "WR-03",
     "dimension": "专利文体",
     "severity": "minor",
     "target_section": "prior_art_defects",
     "target_path": "prior_art_defects",
     "issue": "存在可能导致边界不清的相对或不确定用语：可能",
     "risk": "若无测量方法、参照对象或范围限定，技术特征可能不清楚。",
     "suggested_revision": "在原始材料支持范围内补充参照对象、计算方式、阈值或数值范围。",
     "evidence_ids": [],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 1.0,
     "source": "rule"
    },
    {
     "finding_id": "C-AI-02",
     "check_id": "AI-02",
     "dimension": "AI算法专项",
     "severity": "major",
     "target_section": "implementation_boundaries",
     "target_path": "implementation_boundaries",
     "issue": "模型边界总体清楚：VLM包括LLM骨干、视觉编码器和跨模态投影；向量仅在语言骨干提取/注入，视觉编码器和VLM骨干冻结，仅优化注入向量。但推理阶段部署边界仍有关键未决点，尤其是Transformer内部hook位置、prefill与decode阶段覆盖范围、生成标记范围，这会影响模型结构和推理边界的清楚性。",
     "risk": "应说明相关模型模块、训练或推理阶段、参数更新范围及部署边界。",
     "suggested_revision": "明确目标VLM中语言骨干的被hook模块名称和张量位置，例如块输入/注意力输出/MLP后/块输出；说明注入是否作用于prompt prefill、首个生成token和全部后续生成token；说明仅语言token还是包含图像占位token对应位置。",
     "evidence_ids": [
      "E0002",
      "E0093",
      "E0095",
      "E0101",
      "E0118",
      "E0122",
      "E0259"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.82,
     "source": "llm"
    },
    {
     "finding_id": "C-AI-03",
     "check_id": "AI-03",
     "dimension": "AI算法专项",
     "severity": "major",
     "target_section": "S110",
     "target_path": "detailed_steps",
     "issue": "推理向量核心公式、变量h_l、δ_l、r_l、静态注入、可学习注入、注意力头输出级向量和主要训练超参数已披露，达到部分可实施程度；但可学习适配的核心损失变量z_l^R、z_l^S及λ_rec未定义完整，停止条件也未披露，导致可学习算法特征仍不足。",
     "risk": "核心算法公式、变量、张量位置、损失或约束及参数选择应达到可实施程度。",
     "suggested_revision": "补充z_l^R与z_l^S分别对应哪一路径、哪一层、哪一标记区间、注入前后还是投影后的张量；给出λ_rec具体数值或选择规则；明确训练停止条件，例如固定6个epoch或开发集指标早停。",
     "evidence_ids": [
      "E0075",
      "E0912",
      "E0913",
      "E0914",
      "E0915",
      "E0916",
      "E0922",
      "E0923",
      "E0932"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.87,
     "source": "llm"
    }
   ]
  },
  "final": {
   "score": 40,
   "passed": false,
   "counts": {
    "pass": 24,
    "needs_human_review": 5,
    "fail": 1
   },
   "findings": [
    {
     "finding_id": "C-UE-01",
     "check_id": "UE-01",
     "dimension": "无依据扩写",
     "severity": "major",
     "target_section": "系统实现",
     "target_path": "system_implementation",
     "issue": "原始材料披露了LIFT算法流程、PyTorch实现、向量提取和注入，但未直接披露这些系统模块和接口命名，也未披露“存储介质”的实现内容。虽然多数模块可由方法步骤概括得到，但“接口/模块/处理器挂钩”等系统化实现细节属于专利文本新增概括，当前证据不足以确认均有原始材料支持，可能影响无依据扩写风险。",
     "risk": "不得补造原材料未披露的部件、接口、参数、步骤、附图内容或应用范围。",
     "suggested_revision": "将system_implementation和data_and_interfaces中的模块/接口表述改为“可由处理器执行的步骤”或“可选实现方式”，删除未由原文支持的具体接口命名；若保留系统、存储介质主题，请由发明人补充原始实现文档、代码结构或系统架构证据。",
     "evidence_ids": [
      "E0063",
      "E0064",
      "E0070",
      "E0071",
      "E0072",
      "E0093",
      "E0118",
      "E0122",
      "E0362"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.72,
     "source": "llm"
    },
    {
     "finding_id": "F-KNOWN_TECHNICAL_GAPS",
     "check_id": "EN-03",
     "dimension": "充分公开",
     "severity": "major",
     "target_section": "实现边界与发明人确认",
     "target_path": "inventor_confirmation_items",
     "issue": "Generator已识别出19项原始材料未充分披露的技术细节",
     "risk": "若这些细节属于实现发明不可缺少的条件，当前材料可能无法满足充分公开或权利要求支持要求。",
     "suggested_revision": "逐项向发明人确认并补充证据；当前重点包括：未见直接证据支持目标VLM与基础LLM层数或隐藏维度不一致时的层映射、投影矩阵或维度对齐策略；不得写成确定实施步骤。；未见直接证据支持不同tokenizer之间的答案token对齐或重分词策略；不得写成确定实施步骤。；未见直接证据支持静态隐藏状态注入是否作用于所有语言token、仅生成token、仅答案token或特定位置；除“language-token hidden states/selected language-model layer”外不应细化。；未见直接证据支持多层同时注入规则；论文主流程为选择层注入，注意力实验也按选层评测。；另有15项",
     "evidence_ids": [],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 1.0,
     "source": "rule"
    },
    {
     "finding_id": "C-EN-04",
     "check_id": "EN-04",
     "dimension": "充分公开",
     "severity": "major",
     "target_section": "数据和接口",
     "target_path": "data_and_interfaces",
     "issue": "核心算法公式和主流程已披露到可理解程度，但可重复实施仍存在关键缺口：答案区间程序化识别、多标记答案对齐、两条路径分词不一致时处理规则、z_l^R/z_l^S精确定义、λ_rec数值和停止条件未完整披露。交底书已识别这些缺口，但当前材料不足以确认本领域人员可稳定复现实验和可学习适配过程。",
     "risk": "算法输入、计算规则、关键条件、输出和异常处理应足以让本领域人员实现。",
     "suggested_revision": "补充答案区间识别伪代码、token对齐规则、特殊token和分词不一致处理；补充z_l^R、z_l^S的张量来源、层位置、损失计算范围、λ_rec取值和训练停止条件。",
     "evidence_ids": [
      "E0073",
      "E0074",
      "E0075",
      "E0081",
      "E0083",
      "E0097",
      "E0115",
      "E0118",
      "E0912",
      "E0913",
      "E0915",
      "E0916",
      "E0932"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.74,
     "source": "llm"
    },
    {
     "finding_id": "C-CS-03",
     "check_id": "CS-03",
     "dimension": "保护范围支撑",
     "severity": "major",
     "target_section": "技术领域",
     "target_path": "technical_field",
     "issue": "方法主题和注意力级替代方案有实施方式和证据支撑，但“系统和存储介质”保护主题、以及面向任意视觉语言模型/部署场景的上位概括，目前主要由方法流程推导，缺少对应系统架构、存储介质执行逻辑或更广泛模型验证证据。交底书虽设置了实施边界，但保护范围支撑仍需人工确认。",
     "risk": "方法、系统、介质及上位概括均应由实施方式和证据支持。",
     "suggested_revision": "在说明书中为系统和存储介质分别补充与方法步骤一一对应的处理器、存储器、指令执行关系，并将模型范围限定为“对应基础语言模型与目标视觉语言模型具有可匹配语言骨干/隐藏维度的情形”；如主张更宽范围，补充异构模型映射或更多验证证据。",
     "evidence_ids": [
      "E0063",
      "E0066",
      "E0093",
      "E0125",
      "E0257",
      "E0259",
      "E0410",
      "E0922",
      "E0923",
      "E0937"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.7,
     "source": "llm"
    },
    {
     "finding_id": "C-AI-02",
     "check_id": "AI-02",
     "dimension": "AI算法专项",
     "severity": "major",
     "target_section": "发明人确认事项",
     "target_path": "inventor_confirmation_items",
     "issue": "模型模块、训练/推理边界和参数更新范围已有基本说明：VLM架构包括视觉编码器、投影模块和语言骨干；推理向量提取和注入位于语言侧；可学习适配仅优化注入向量，VLM骨干和视觉编码器冻结。但具体Transformer块挂接点、作用时间步和标记范围仍需发明人确认，属于实现精度缺口。",
     "risk": "应说明相关模型模块、训练或推理阶段、参数更新范围及部署边界。",
     "suggested_revision": "补充主隐藏状态注入在Transformer块中的精确位置、是否作用于prefill阶段、首个生成token及后续全部语言token；明确注意力级注入的头选择范围和模块内部挂接位置。",
     "evidence_ids": [
      "E0002",
      "E0093",
      "E0095",
      "E0101",
      "E0118",
      "E0122",
      "E0125",
      "E0932"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.76,
     "source": "llm"
    },
    {
     "finding_id": "C-AI-03",
     "check_id": "AI-03",
     "dimension": "AI算法专项",
     "severity": "major",
     "target_section": "具体步骤",
     "target_path": "detailed_steps",
     "issue": "δ_l、r_l、静态/可学习注入和注意力头输出级注入公式已有直接证据，变量含义基本清楚。但可学习适配的z_l^R、z_l^S张量位置、λ_rec数值、停止条件，以及答案标记对齐异常规则未披露完整，导致算法特征尚未达到完全可重复实施程度。",
     "risk": "核心算法公式、变量、张量位置、损失或约束及参数选择应达到可实施程度。",
     "suggested_revision": "补充z_l^R/z_l^S的定义、张量维度和取值位置，给出λ_rec具体数值或选择规则；补充答案token对齐伪代码及异常处理；说明θ_l是单层向量、逐层向量还是按选定层分别训练。",
     "evidence_ids": [
      "E0075",
      "E0076",
      "E0081",
      "E0083",
      "E0912",
      "E0913",
      "E0915",
      "E0916",
      "E0922",
      "E0923",
      "E0932"
     ],
     "auto_fixable": false,
     "requires_inventor_confirmation": true,
     "confidence": 0.74,
     "source": "llm"
    }
   ],
   "dimensions": [
    {
     "dimension": "证据可追溯性",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "事实一致性",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "无依据扩写",
     "score": 90,
     "finding_count": 1
    },
    {
     "dimension": "完整性与形式",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "技术逻辑闭环",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "充分公开",
     "score": 80,
     "finding_count": 2
    },
    {
     "dimension": "保护范围支撑",
     "score": 90,
     "finding_count": 1
    },
    {
     "dimension": "可专利客体",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "单一性",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "一致性",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "附图一致性",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "专利文体",
     "score": 100,
     "finding_count": 0
    },
    {
     "dimension": "AI算法专项",
     "score": 80,
     "finding_count": 2
    }
   ]
  },
  "checklist": [
   {
    "check_id": "EV-01",
    "dimension": "证据可追溯性",
    "title": "核心章节具有证据映射",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "EV-02",
    "dimension": "证据可追溯性",
    "title": "数值与实验结论可逐项追溯",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "fail",
    "final_status": "pass",
    "resolution": "resolved",
    "initial_reason": "主要实验准确率、评测样本量、bootstrap统计量、随机向量对照、注意力级注入结果和可学习适配超参数均有表格或正文证据支持；但“每个支持来源采样500个样本”在当前证据列表中未见直接证据编号，属于数值参数不可逐项追溯。",
    "final_reason": "主要数值与实验结论均能追溯至表格或方法证据：六个评测集样本量、主实验准确率、平均准确率、同范数随机向量对照、注意力级注入结果、100个开发样本选层、生成配置和bootstrap统计量均有直接证据支持。"
   },
   {
    "check_id": "FC-01",
    "dimension": "事实一致性",
    "title": "技术事实与原始材料一致",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "交底书关于LIFT对象、Reasoner/Solver双路径、答案标记隐藏状态差分、逐层平均、来源模型、冻结VLM骨干、层选择、静态/可学习注入、注意力级替代公式及主要实验事实，与原始材料一致，未发现改变原意的明确事实错误。",
    "final_reason": "交底书的对象、步骤、公式、模型边界和实验设置与原始论文材料基本一致；核心公式δ_l、r_l、静态/可学习加法注入均有对应证据。交底书还明确保留了若干未披露细节作为边界或确认事项，未将其写成已证实事实。"
   },
   {
    "check_id": "FC-02",
    "dimension": "事实一致性",
    "title": "机理与效果使用审慎表述",
    "severity": "minor",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "交底书对机理和效果总体采用了审慎限定，例如使用“可能”“在论文所测试的模型和数据集上”“定性观察”“不构成无条件性能保证”等表述，并在边界中说明不能直接修复视觉感知或定位错误；未将推测性解释写成普遍确定机理。",
    "final_reason": "交底书对机理和效果采用了审慎限定，例如将机制解释限定为“可能”“表明在所测配置下”，并明确效果仅限论文披露模型、支持集、基准、层选择和解码配置；对视觉感知错误不能直接修复也作出限制，未把推测性解释写成普遍确定机理。"
   },
   {
    "check_id": "UE-01",
    "dimension": "无依据扩写",
    "title": "不存在无依据技术扩写",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "needs_human_review",
    "resolution": "new_failure",
    "initial_reason": "交底书未将这些未披露内容写成确定实施方案，而是列入implementation_boundaries和inventor_confirmation_items；当前未发现补造未披露接口、参数或步骤并作为已验证方案的明确问题。",
    "final_reason": "原始材料披露了LIFT算法流程、PyTorch实现、向量提取和注入，但未直接披露这些系统模块和接口命名，也未披露“存储介质”的实现内容。虽然多数模块可由方法步骤概括得到，但“接口/模块/处理器挂钩”等系统化实现细节属于专利文本新增概括，当前证据不足以确认均有原始材料支持，可能影响无依据扩写风险。"
   },
   {
    "check_id": "CF-01",
    "dimension": "完整性与形式",
    "title": "必要章节完整",
    "severity": "critical",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "CF-02",
    "dimension": "完整性与形式",
    "title": "发明名称简明准确",
    "severity": "minor",
    "evaluator": "rule",
    "initial_status": "fail",
    "final_status": "pass",
    "resolution": "resolved",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "TL-01",
    "dimension": "技术逻辑闭环",
    "title": "技术问题来源明确",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "TL-02",
    "dimension": "技术逻辑闭环",
    "title": "总体方案形成可执行技术链",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "TL-03",
    "dimension": "技术逻辑闭环",
    "title": "问题、特征与效果形成因果闭环",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "主要问题包括不更新VLM骨干复用LLM推理表征、不同长度路径对齐、层敏感和跨模态迁移；对应特征为答案标记差分、支持样本聚合、语言层加法注入、开发集选层和冻结骨干；效果限定为所测配置下平均准确率提升和跨模态任务改善，形成因果闭环。",
    "final_reason": "主要问题、技术特征和效果之间形成闭环：不更新VLM参数的问题对应冻结骨干和加法注入；不同长度序列对齐问题对应仅在答案标记差分；层敏感问题对应开发集选层；效果对应平均准确率提升、跨模态任务改善和随机向量对照。视觉感知错误不能直接修复也已在边界中说明。"
   },
   {
    "check_id": "EN-01",
    "dimension": "充分公开",
    "title": "至少具有一个实施例",
    "severity": "critical",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "EN-02",
    "dimension": "充分公开",
    "title": "实施例达到基本详尽度",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "EN-03",
    "dimension": "充分公开",
    "title": "已知技术缺口已经处理",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "fail",
    "final_status": "fail",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "EN-04",
    "dimension": "充分公开",
    "title": "核心算法和运行步骤可重复实施",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "needs_human_review",
    "final_status": "needs_human_review",
    "resolution": "unchanged",
    "initial_reason": "核心向量计算公式、输入、聚合和注入形式已有披露，但可重复实施仍受关键缺口影响：答案区间/多标记答案对齐和异常分词处理规则未确定；主隐藏状态注入的精确挂接点和作用时间步未限定；可学习适配中z_l^R、z_l^S、λ_rec及停止条件未完整披露。这些缺口会影响本领域人员复现实验和实施系统。",
    "final_reason": "核心算法公式和主流程已披露到可理解程度，但可重复实施仍存在关键缺口：答案区间程序化识别、多标记答案对齐、两条路径分词不一致时处理规则、z_l^R/z_l^S精确定义、λ_rec数值和停止条件未完整披露。交底书已识别这些缺口，但当前材料不足以确认本领域人员可稳定复现实验和可学习适配过程。"
   },
   {
    "check_id": "CS-01",
    "dimension": "保护范围支撑",
    "title": "关键必要技术特征已提炼",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "CS-02",
    "dimension": "保护范围支撑",
    "title": "替代实施方式和参数层级已整理",
    "severity": "note",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "CS-03",
    "dimension": "保护范围支撑",
    "title": "概括范围受到说明书支持",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "needs_human_review",
    "final_status": "needs_human_review",
    "resolution": "unchanged",
    "initial_reason": "方法主题有较充分实施方式和实验支撑；系统主题可由支持样本管理、双路径前向、激活采集、向量计算、选层、适配、注入和评测模块支撑。但“存储介质”作为保护主题仅在标题出现，交底书未明确其承载的程序指令、处理器执行流程或与方法步骤的对应关系；上位概括到任意视觉语言模型也已通过边界限制，但仍需在权利要求撰写时避免超出两类已验证模型和对应模型关系。",
    "final_reason": "方法主题和注意力级替代方案有实施方式和证据支撑，但“系统和存储介质”保护主题、以及面向任意视觉语言模型/部署场景的上位概括，目前主要由方法流程推导，缺少对应系统架构、存储介质执行逻辑或更广泛模型验证证据。交底书虽设置了实施边界，但保护范围支撑仍需人工确认。"
   },
   {
    "check_id": "ES-01",
    "dimension": "可专利客体",
    "title": "方案属于技术性解决方案",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "UN-01",
    "dimension": "单一性",
    "title": "共同技术构思可机械识别",
    "severity": "note",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "UN-02",
    "dimension": "单一性",
    "title": "各保护主题具有同一总的发明构思",
    "severity": "minor",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "方法、系统、介质及静态/可学习/注意力级替代方案均围绕同一总的发明构思：通过Reasoner-Solver语言侧答案表征差形成推理向量，并在目标VLM语言侧激活中加法注入；各保护主题共享相同或相应的特定技术特征。",
    "final_reason": "各保护主题均围绕同一总的发明构思：基于Reasoner/Solver路径在语言侧答案表征差分得到推理向量，并在目标VLM语言侧进行轻量加法干预。静态、可学习、不同向量来源、注意力头输出级注入及系统实现共享相同或相应的特定技术特征。"
   },
   {
    "check_id": "CO-01",
    "dimension": "一致性",
    "title": "核心术语统一",
    "severity": "minor",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "DR-01",
    "dimension": "附图一致性",
    "title": "正文引用与附图说明对应",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "DR-02",
    "dimension": "附图一致性",
    "title": "附图内容具有原始证据",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "附图描述的总体流程、双路径提取、静态迁移、可学习适配、三种向量来源、注意力级注入、实验结果和层/相似度分析均可由原始图、表、公式或方法文字支撑；未发现附图节点、关系或实验图形明显超过原始材料。",
    "final_reason": "图1至图5的数量、主题和内容均可追溯至原始材料中的图证据：动机图、方法概览图、案例图、跨层余弦相似度图和逐层性能图均有对应figure证据或正文说明。未发现附图数量、节点关系或实验图形超出原始材料支持。"
   },
   {
    "check_id": "WR-01",
    "dimension": "专利文体",
    "title": "使用专利技术文体",
    "severity": "minor",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "WR-02",
    "dimension": "专利文体",
    "title": "避免无条件绝对化表述",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "WR-03",
    "dimension": "专利文体",
    "title": "相对与不确定用语边界清楚",
    "severity": "minor",
    "evaluator": "rule",
    "initial_status": "fail",
    "final_status": "pass",
    "resolution": "resolved",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "AI-01",
    "dimension": "AI算法专项",
    "title": "AI输入和输出定义完整",
    "severity": "major",
    "evaluator": "rule",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "",
    "final_reason": ""
   },
   {
    "check_id": "AI-02",
    "dimension": "AI算法专项",
    "title": "模型结构及训练推理边界清楚",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "needs_human_review",
    "final_status": "needs_human_review",
    "resolution": "unchanged",
    "initial_reason": "模型边界总体清楚：VLM包括LLM骨干、视觉编码器和跨模态投影；向量仅在语言骨干提取/注入，视觉编码器和VLM骨干冻结，仅优化注入向量。但推理阶段部署边界仍有关键未决点，尤其是Transformer内部hook位置、prefill与decode阶段覆盖范围、生成标记范围，这会影响模型结构和推理边界的清楚性。",
    "final_reason": "模型模块、训练/推理边界和参数更新范围已有基本说明：VLM架构包括视觉编码器、投影模块和语言骨干；推理向量提取和注入位于语言侧；可学习适配仅优化注入向量，VLM骨干和视觉编码器冻结。但具体Transformer块挂接点、作用时间步和标记范围仍需发明人确认，属于实现精度缺口。"
   },
   {
    "check_id": "AI-03",
    "dimension": "AI算法专项",
    "title": "算法特征披露充分",
    "severity": "major",
    "evaluator": "llm",
    "initial_status": "needs_human_review",
    "final_status": "needs_human_review",
    "resolution": "unchanged",
    "initial_reason": "推理向量核心公式、变量h_l、δ_l、r_l、静态注入、可学习注入、注意力头输出级向量和主要训练超参数已披露，达到部分可实施程度；但可学习适配的核心损失变量z_l^R、z_l^S及λ_rec未定义完整，停止条件也未披露，导致可学习算法特征仍不足。",
    "final_reason": "δ_l、r_l、静态/可学习注入和注意力头输出级注入公式已有直接证据，变量含义基本清楚。但可学习适配的z_l^R、z_l^S张量位置、λ_rec数值、停止条件，以及答案标记对齐异常规则未披露完整，导致算法特征尚未达到完全可重复实施程度。"
   },
   {
    "check_id": "AI-04",
    "dimension": "AI算法专项",
    "title": "算法特征与技术效果存在因果关系",
    "severity": "minor",
    "evaluator": "llm",
    "initial_status": "pass",
    "final_status": "pass",
    "resolution": "unchanged",
    "initial_reason": "算法特征与技术效果之间已有因果说明和验证：答案标记隐藏状态差分作为推理轨迹引起的表征变化，加法注入在冻结骨干下改善六基准平均准确率；开发集选层对应层敏感问题；随机同范数对照和可学习初始化对照支持效果并非仅由扰动范数或可训练参数导致；案例分析仅作为定性观察并有限定。",
    "final_reason": "算法特征与技术效果之间有可验证因果链条：答案标记差分形成推理向量、语言侧注入带来平均准确率提升；同范数随机向量对照支持效果并非仅由扰动范数解释；案例分析说明部分中间推理行为受影响。交底书同时将效果限定于已测配置，因果表述较审慎。"
   }
  ]
 },
 "revision": {
  "attempts": [
   {
    "round_number": 1,
    "check_id": "EV-02",
    "outcome": "modified",
    "reason": "删除了当前证据列表中缺少直接编号支撑的固定采样数表述，保留了支持样本、正确样本筛选和离线提取流程，避免数值参数不可逐项追溯。",
    "allowed_target_paths": [
     "detailed_steps"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0086",
     "E0136",
     "E0355"
    ],
    "changes": [
     {
      "action_id": "R1-EV-02-001",
      "target_path": "detailed_steps",
      "before": "。论文披露通常针对每个支持来源采样500个样本。",
      "after": "",
      "finding_ids": [
       "C-EV-02"
      ]
     }
    ]
   },
   {
    "round_number": 1,
    "check_id": "CF-02",
    "outcome": "modified",
    "reason": "将发明名称删除“一种”“跨模型”“激活”“存储”等非必要限定，保留语言侧推理向量提取、视觉语言模型干预及方法/系统/介质的主题类型，使名称更简明且未引入证据外技术事实。",
    "allowed_target_paths": [
     "invention_title"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0063",
     "E0093",
     "E0118",
     "E0122"
    ],
    "changes": [
     {
      "action_id": "R1-CF-02-001",
      "target_path": "invention_title",
      "before": "一种跨模型语言侧推理向量提取及视觉语言模型激活干预方法、系统和存储介质",
      "after": "语言侧推理向量提取及视觉语言模型干预方法、系统和介质",
      "finding_ids": [
       "F-TITLE_LONG"
      ]
     }
    ]
   },
   {
    "round_number": 1,
    "check_id": "EN-03",
    "outcome": "blocked",
    "reason": "本次 finding 仅说明 Generator 识别出19项原始材料未充分披露的技术细节，但输入中只列出部分重点事项并以“另有15项”概括，未提供其余缺口的具体内容。当前 allowed_target_paths 仅允许修改 inventor_confirmation_items；在缺少完整缺口清单的情况下，无法判断应逐项新增哪些发明人确认事项，也不能猜测补写技术事实或确认问题。因此本检查项无法在现有证据范围内完整闭环。",
    "allowed_target_paths": [
     "inventor_confirmation_items"
    ],
    "requested_materials": [
     "请提供 Generator 识别出的19项原始材料未充分披露技术细节的完整逐项清单，包括每项对应的具体技术缺口、所在交底书字段或章节、是否已有证据支持以及建议向发明人确认的问题。",
     "请发明人逐项确认以下已明确缺口：目标VLM与基础LLM层数或隐藏维度不一致时是否允许迁移；如允许，请提供层映射、投影矩阵或维度对齐策略；如不允许，请确认模型对应关系限制。",
     "请发明人逐项确认以下已明确缺口：不同 tokenizer 之间的答案 token 对齐或重分词策略，包括特殊标记、多 token 答案和两条路径分词不一致时的处理规则。",
     "请发明人逐项确认以下已明确缺口：静态隐藏状态注入作用的语言 token 范围，是全部 language-token hidden states、仅生成 token、仅答案 token、首个生成 token 还是其他特定位置。",
     "请发明人逐项确认以下已明确缺口：是否存在多层同时注入实施规则；如存在，请提供层组合选择、各层向量使用方式和评测证据；如不存在，请确认主流程限定为选择单层注入。"
    ],
    "evidence_ids": [],
    "changes": []
   },
   {
    "round_number": 1,
    "check_id": "EN-04",
    "outcome": "blocked",
    "reason": "现有证据仅支持双路径输入、最终答案区间内对齐答案标记读取、差分聚合、推理期在所选语言模型层进行自回归解码加法注入、仅修改语言标记隐藏状态以及可学习适配使用对齐损失等原则性内容；但未给出答案区间程序化定位和异常对齐规则、主隐藏状态注入在Transformer块内的精确挂接点及覆盖时间步、z_l^R与z_l^S的张量来源、λ_rec具体数值等关键实施细节。若直接改写为确定规则会引入证据中不存在的技术事实，无法在仅允许修改data_and_interfaces字段的条件下安全解决EN-04充分公开问题。",
    "allowed_target_paths": [
     "data_and_interfaces"
    ],
    "requested_materials": [
     "请发明人提供final_answer在C_R=(Q,T,A)和C_S=(Q,A)中的程序化起止定位规则，包括答案文本匹配、boxed答案解析后回填到token区间、重复答案文本出现时的选择规则。",
     "请发明人提供多标记答案在两条路径之间的token级对齐算法，包括使用字符跨度映射、token offset映射还是其他方法。",
     "请发明人提供特殊标记、空白符、分词器附加前缀、数字/选项答案被拆分不一致时的处理规则，以及无法唯一对齐时是丢弃样本、截断、重分词还是报错终止。",
     "请发明人确认主隐藏状态注入在Transformer块中的精确挂接点，例如块输入、注意力残差后、MLP残差后或块输出，并说明对应实现接口。",
     "请发明人确认主隐藏状态注入覆盖的自回归阶段和标记范围，包括是否作用于prompt prefill、首个生成标记以及全部后续生成语言标记。",
     "请发明人提供可学习适配中z_l^R和z_l^S的完整定义，包括其来自目标VLM还是向量来源模型、来自哪一层/哪一token区间/是否经过平均或归一化、是否在注入前后计算。",
     "请发明人提供λ_rec的具体数值或确定方法。",
     "请发明人确认可学习适配的停止条件是否仅为固定6个epoch，或还包括开发集早停、损失阈值、无改善轮数等规则；如有，请提供具体阈值和判定方式。"
    ],
    "evidence_ids": [
     "E0073",
     "E0074",
     "E0075",
     "E0081",
     "E0097",
     "E0118",
     "E0122",
     "E0912",
     "E0913",
     "E0915"
    ],
    "changes": []
   },
   {
    "round_number": 1,
    "check_id": "CS-03",
    "outcome": "modified",
    "reason": "在本次仅允许修改 invention_title 的约束下，无法向 system_implementation 等字段补充存储介质承载程序指令及处理器执行步骤的内容。为避免标题中的“介质”保护主题超出说明书支持范围，依据现有证据仅保留已由方法流程和系统模块支撑的方法、系统主题。",
    "allowed_target_paths": [
     "invention_title"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0063",
     "E0066",
     "E0093",
     "E0095",
     "E0122",
     "E0257",
     "E0259"
    ],
    "changes": [
     {
      "action_id": "R1-CS-03-001",
      "target_path": "invention_title",
      "before": "、系统和介质",
      "after": "和系统",
      "finding_ids": [
       "C-CS-03"
      ]
     }
    ]
   },
   {
    "round_number": 1,
    "check_id": "WR-03",
    "outcome": "modified",
    "reason": "已仅针对 WR-03 指出的“可能”不确定用语进行局部替换，并限定在允许修改的 background 与 prior_art_defects 字段内。修改依据论文材料中关于多模态扩展后推理失败情形、VLM-derived 向量低于 LLM-derived 向量以及多模态对齐影响语言侧推理表征的记载，未引入新的技术参数、步骤或实验结果。",
    "allowed_target_paths": [
     "background",
     "prior_art_defects"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0009",
     "E0010",
     "E0011",
     "E0176",
     "E0212",
     "E0255"
    ],
    "changes": [
     {
      "action_id": "R1-WR-03-001",
      "target_path": "background",
      "before": "多模态对齐可能改变语言骨干的行为及内部表征，使对应视觉语言模型在纯文本推理或多步推理过程中出现中间变量改变、条件遗漏、数值复制错误或输出目标偏离等情况。",
      "after": "论文材料记载，经过多模态扩展后，对应视觉语言模型在纯文本推理或多步推理过程中存在中间变量改变、条件遗漏、数值复制错误或输出目标偏离等失败情形。",
      "finding_ids": [
       "F-AMBIGUOUS_BACKGROUND"
      ]
     },
     {
      "action_id": "R1-WR-03-002",
      "target_path": "prior_art_defects",
      "before": "所提取方向可能受到多模态对齐造成的表征变化影响；",
      "after": "所提取方向会混入多模态对齐后的语言侧表征状态；",
      "finding_ids": [
       "F-AMBIGUOUS_PRIOR_ART_DEFECTS"
      ]
     }
    ]
   },
   {
    "round_number": 1,
    "check_id": "AI-02",
    "outcome": "modified",
    "reason": "现有证据已明确：注入发生在推理时的自回归解码阶段，位置是所选语言模型层，且仅修改语言 token 隐藏状态并冻结VLM参数；同时支持样本不附加到评测提示。将原句收窄并改写为证据可支持的边界描述后，可消除该处未决表述。",
    "allowed_target_paths": [
     "implementation_boundaries"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0118",
     "E0122",
     "E0325"
    ],
    "changes": [
     {
      "action_id": "R1-AI-02-001",
      "target_path": "implementation_boundaries",
      "before": "主隐藏状态注入的Transformer模块内部挂接点、作用于提示预填充阶段还是仅作用于生成阶段，以及具体覆盖哪些生成标记，现有材料未完整限定。",
      "after": "主隐藏状态注入在推理阶段的自回归解码过程中，于所选语言模型层实施加法式干预；该过程仅修改语言 token 隐藏状态，不更新 VLM 参数，且支持样本及其提取轨迹不作为评测提示中的上下文示例。",
      "finding_ids": [
       "C-AI-02"
      ]
     }
    ]
   },
   {
    "round_number": 1,
    "check_id": "AI-03",
    "outcome": "blocked",
    "reason": "当前证据仅披露可学习适配损失公式L_rec=||z_l^R-z_l^S||_2^2、L=λ_rec L_rec，以及训练6个epoch等超参数；未披露z_l^R、z_l^S对应的具体路径、层、标记区间及张量位置，也未披露λ_rec的具体数值或选择规则。仅凭现有证据无法完整补足可学习适配算法特征，若猜测定义或参数会引入证据中不存在的技术事实。",
    "allowed_target_paths": [
     "detailed_steps"
    ],
    "requested_materials": [
     "请发明人补充z_l^R的完整定义：对应Reasoner路径还是其他路径、所在语言层l、适用的答案标记区间、是注入前还是注入后的隐藏状态、是否经过投影或池化、张量维度及批内/标记维度的归约方式。",
     "请发明人补充z_l^S的完整定义：对应Solver路径还是其他路径、所在语言层l、适用的答案标记区间、是注入前还是注入后的隐藏状态、是否经过投影或池化、张量维度及批内/标记维度的归约方式。",
     "请发明人补充λ_rec的具体数值，或可实施的选择规则、搜索范围及选择依据。",
     "请发明人确认可学习适配的训练停止条件是否为固定训练6个epoch；如存在开发集早停、最佳模型选择或其他终止规则，请补充对应指标、阈值和判定方式。"
    ],
    "evidence_ids": [
     "E0915",
     "E0932",
     "E0098"
    ],
    "changes": []
   },
   {
    "round_number": 2,
    "check_id": "EN-03",
    "outcome": "modified",
    "reason": "现有条目整体属于发明人确认事项，但其中“每个支持源通常采样500个样本”的表述缺少当前证据支撑。已将该条收窄为仅确认支持样本数量不足时的处理规则与规模一致性，避免引入未披露事实。",
    "allowed_target_paths": [
     "inventor_confirmation_items"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0086",
     "E0095",
     "E0122",
     "E0137",
     "E0139",
     "E0410",
     "E0915",
     "E0916",
     "E0258"
    ],
    "changes": [
     {
      "action_id": "R2-EN-03-001",
      "target_path": "inventor_confirmation_items",
      "before": "请确认筛选后支持样本数量N不足时的补采样或终止条件，并说明论文所述每个支持源通常采样500个样本是否适用于全部实施例。",
      "after": "请确认筛选后支持样本数量N不足时的补采样、下限阈值或终止条件，并说明该支持样本规模设置是否在全部实施例中一致。",
      "finding_ids": [
       "F-KNOWN_TECHNICAL_GAPS"
      ]
     }
    ]
   },
   {
    "round_number": 2,
    "check_id": "EN-04",
    "outcome": "blocked",
    "reason": "本次只能修改 data_and_interfaces。现有证据能够支持双路径输入、仅读取对齐最终答案标记、逐层差分聚合、所选语言模型层自回归解码注入及冻结骨干等内容，但不足以确定 finding C-EN-04 指出的关键可重复实施缺口，尤其是答案区间程序化识别规则、分词不一致/异常对齐处理、主隐藏状态注入在Transformer块中的精确挂接点、生成时间步覆盖范围、lambda_rec具体数值以及z_l^R/z_l^S的精确定义。若在 data_and_interfaces 中直接补全这些规则将引入证据中不存在的技术事实，因此不能安全改稿。",
    "allowed_target_paths": [
     "data_and_interfaces"
    ],
    "requested_materials": [
     "请提供final_answer span的程序化定位规则，包括如何从C_R=(Q,T,A)和C_S=(Q,A)的token序列中确定答案起始位置和结束位置。",
     "请提供特殊标记处理规则，包括BOS/EOS、分隔符、提示模板标记、boxed答案标记或其他格式标记是否计入最终答案区间。",
     "请提供多标记答案在两条路径之间的对齐算法，以及两路径分词结果不一致、答案token数量不同或无法一一对齐时的跳过、重分词、报错或补采样规则。",
     "请确认支持样本经正确性筛选后数量N不足、答案区间为空或无可对齐答案标记时的终止条件、补采样流程或最小样本阈值。",
     "请确认主隐藏状态注入在Transformer块中的精确挂接点，例如块输入、注意力残差后、MLP残差后、块输出或其他模块接口。",
     "请确认主隐藏状态注入覆盖的自回归时间步和标记范围，包括是否作用于prefill阶段、首个生成标记以及全部后续语言token。",
     "请提供可学习适配中z_l^R和z_l^S的张量来源、所在层、所在token位置、是否为注入前/注入后隐藏状态及其维度定义。",
     "请提供lambda_rec的具体数值或确定方式。",
     "请提供可学习适配训练停止条件，包括是否固定6个epoch、是否使用开发集早停、收敛阈值或异常停止规则。"
    ],
    "evidence_ids": [
     "E0073",
     "E0074",
     "E0075",
     "E0095",
     "E0115",
     "E0118",
     "E0912",
     "E0913",
     "E0915",
     "E0916"
    ],
    "changes": []
   },
   {
    "round_number": 2,
    "check_id": "DR-02",
    "outcome": "modified",
    "reason": "已将附图说明收窄为原始证据明确列明的5幅论文图：LIFT动机、方法概览、代表性案例、跨层余弦相似度和逐层性能图；删除新增且缺少原始图形证据的系统架构、静态迁移流程、可学习适配流程、注入层选择、三种向量来源、注意力头注入和独立实验对比图号。修改未引入新的技术事实。",
    "allowed_target_paths": [
     "drawing_descriptions"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0938",
     "E0939",
     "E0940",
     "E0941",
     "E0942",
     "E0924",
     "E0925"
    ],
    "changes": [
     {
      "action_id": "R2-DR-02-001",
      "target_path": "drawing_descriptions",
      "before": "图1为本发明系统总体架构图，示出支持样本集、向量来源模型、双路径前向处理模块、隐藏状态读取模块、推理向量聚合模块、注入层选择模块、目标视觉语言模型和生成评测模块。",
      "after": "图1为LIFT动机示意图，示出多模态对齐可能改变视觉语言模型中的语言侧推理方向，以及来自基础语言模型的推理向量可作为对齐后视觉语言模型中的轻量干预方向。",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-002",
      "target_path": "drawing_descriptions",
      "before": "图2为推理向量提取流程图，示出推理路径C_R=(Q,T,A)和求解路径C_S=(Q,A)，以及最终答案标记对齐、逐层差分、答案标记平均和支持样本平均过程。",
      "after": "图2为LIFT方法概览图，示出各层中Reasoner路径与Solver路径的隐藏状态差分及平均以获得Reasoning Vector、可学习适配仅优化注入向量并冻结视觉语言模型骨干，以及推理时向选定视觉语言模型层注入向量。",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-003",
      "target_path": "drawing_descriptions",
      "before": "图3为静态向量迁移流程图，示出从基础语言模型形成逐层推理向量并将所选层向量注入对应视觉语言模型语言骨干的过程。",
      "after": "图3为代表性推理修复案例图。",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-004",
      "target_path": "drawing_descriptions",
      "before": "图4为可学习向量适配流程图，示出以提取向量初始化注入参数、冻结视觉语言模型骨干及视觉编码器并仅更新注入向量的过程。",
      "after": "图4为GSM8K上基础语言模型来源向量与视觉语言模型来源向量的跨层余弦相似度图。",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-005",
      "target_path": "drawing_descriptions",
      "before": "图5为注入层选择示意图，示出在留出开发子集上分别测试候选语言层并固定最佳层用于最终评测的过程。",
      "after": "图5为基础语言模型来源向量与视觉语言模型来源向量在六个数据集上平均的逐层性能图。",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-006",
      "target_path": "drawing_descriptions",
      "before": "图6为三种向量来源对照图，示出LLM-derived、VLM-derived和VLM-MM三条提取路径。",
      "after": "",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-007",
      "target_path": "drawing_descriptions",
      "before": "图7为注意力头输出级替代实施方式示意图，示出头级输出差分、聚合和生成语言标记位置的加法注入。",
      "after": "",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-008",
      "target_path": "drawing_descriptions",
      "before": "图8为实验结果对比图，示出两个目标视觉语言模型在六个基准上的Baseline、静态向量和可学习向量平均准确率。",
      "after": "",
      "finding_ids": [
       "C-DR-02"
      ]
     },
     {
      "action_id": "R2-DR-02-009",
      "target_path": "drawing_descriptions",
      "before": "图9为跨层余弦相似度和层敏感性分析图，示出基础语言模型来源向量与视觉语言模型来源向量的跨层关系及不同注入层对应的性能变化。",
      "after": "",
      "finding_ids": [
       "C-DR-02"
      ]
     }
    ]
   },
   {
    "round_number": 2,
    "check_id": "WR-03",
    "outcome": "modified",
    "reason": "已在允许字段 prior_art_defects 内，将含有不确定用语“可能”的句子改为基于证据的确定表述，并用论文披露的层敏感性、逐层评测和留出开发子集选层协议限定边界；未处理 WR-03 以外问题。",
    "allowed_target_paths": [
     "prior_art_defects"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0114",
     "E0115",
     "E0116",
     "E0246",
     "E0247"
    ],
    "changes": [
     {
      "action_id": "R2-WR-03-001",
      "target_path": "prior_art_defects",
      "before": "激活干预对注入层敏感，任意选取语言层可能导致干预效果降低，甚至低于未干预基线。",
      "after": "激活干预对注入层敏感；在论文逐层评测配置下，不同语言层的干预效果存在波动，因此需要通过留出开发子集确定注入层。",
      "finding_ids": [
       "F-AMBIGUOUS_PRIOR_ART_DEFECTS"
      ]
     }
    ]
   },
   {
    "round_number": 2,
    "check_id": "AI-02",
    "outcome": "blocked",
    "reason": "现有证据仅支持说明VLM包含语言骨干、视觉编码器和跨模态投影模块；可学习适配仅优化注入向量且冻结VLM骨干和视觉编码器；推理时在所选语言模型层进行加法式干预并仅修改language-token hidden states、不更新VLM参数。证据未披露主隐藏状态注入在Transformer块内的精确挂接点，也未披露静态注入覆盖prefill、首个生成token及后续生成token的具体时间步边界，无法在不猜测的情况下补足AI-02所需的训练/推理工程边界。",
    "allowed_target_paths": [
     "implementation_boundaries"
    ],
    "requested_materials": [
     "请发明人确认主隐藏状态注入在Transformer块中的精确挂接点：块输入、注意力残差后、MLP残差后、块输出或其他具体张量位置。",
     "请发明人确认静态隐藏状态注入是否作用于提示预填充阶段prefill。",
     "请发明人确认静态隐藏状态注入是否作用于首个生成token。",
     "请发明人确认静态隐藏状态注入是否作用于全部后续自回归生成token，或提供停止/跳过规则。",
     "请发明人确认注入token范围是否仅限language token，并说明在图文输入中如何排除视觉token或视觉侧嵌入。",
     "请发明人确认可学习适配得到的θ_l在训练结束后的加载、冻结和推理使用边界，包括推理阶段是否固定θ_l且不再更新。"
    ],
    "evidence_ids": [
     "E0002",
     "E0093",
     "E0095",
     "E0101",
     "E0118",
     "E0122",
     "E0932"
    ],
    "changes": []
   },
   {
    "round_number": 2,
    "check_id": "AI-03",
    "outcome": "blocked",
    "reason": "现有证据仅支持答案标记隐藏状态差、任务级平均、静态/可学习加法注入公式、对齐损失公式以及可学习适配训练超参数。AI-03所指出的可重复实施缺口需要补充z_l^R、z_l^S的精确定义、λ_rec数值、损失计算位置、答案span程序化对齐和异常处理规则、注意力头注入的头选择及挂接位置等事实；这些事实在本次证据中未披露，无法在不猜测的情况下通过修改detailed_steps充分解决。",
    "allowed_target_paths": [
     "detailed_steps"
    ],
    "requested_materials": [
     "请提供可学习适配中z_l^R与z_l^S的来源张量定义，包括取自目标VLM或来源模型的哪一层、哪一前向路径、注入前还是注入后、对应的token范围及张量维度。",
     "请提供L_rec=||z_l^R-z_l^S||_2^2的具体计算方式，包括按token、按样本、按batch的平均或求和规则，以及损失在训练循环中的计算位置。",
     "请提供λ_rec的具体数值或确定规则；如固定为1，请明确说明。",
     "请提供答案最终span的程序化识别规则，包括boxed答案、数值答案、选择项、是非答案、多标记答案的起止位置确定方式。",
     "请提供Reasoner路径与Solver路径答案标记的对齐算法，以及两条路径分词结果不一致、答案为空、答案span识别失败或长度不一致时的异常处理规则。",
     "请确认隐藏状态注入在Transformer语言层中的精确挂接点，是层输入、注意力残差后、MLP残差后、块输出或其他位置，并说明x_l对应的张量形状。",
     "请确认推理阶段注入覆盖的自回归阶段和标记范围，包括是否作用于prefill阶段、首个生成token以及后续全部语言token。",
     "请确认注意力头输出级注入针对全部注意力头还是选定注意力头；如为选定头，请提供选择规则。",
     "请提供注意力头输出级注入的具体挂接位置和张量维度，包括o^(l,m)(t)是在注意力softmax加权后的head输出、head拼接前、输出投影前还是其他位置。"
    ],
    "evidence_ids": [
     "E0075",
     "E0912",
     "E0913",
     "E0915",
     "E0916",
     "E0922",
     "E0923",
     "E0932"
    ],
    "changes": []
   },
   {
    "round_number": 3,
    "check_id": "UE-01",
    "outcome": "modified",
    "reason": "已将data_and_interfaces中被表述为固定字段集合的“对象/存储对象”改为由证据直接支持的数据用途、来源区分、层选择记录和评测记录描述，避免将论文实验信息扩写为未披露的完整接口或存储字段设计。",
    "allowed_target_paths": [
     "data_and_interfaces"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0073",
     "E0074",
     "E0075",
     "E0086",
     "E0093",
     "E0118",
     "E0122",
     "E0325",
     "E0929"
    ],
    "changes": [
     {
      "action_id": "R3-UE-01-001",
      "target_path": "data_and_interfaces",
      "before": "支持样本对象至少包括question、reasoning_trace、final_answer、source_model_id和correctness字段；多模态支持样本还可包括图像输入引用。",
      "after": "支持样本用于提供问题Q、推理轨迹T和最终答案A，并按照向量来源模型的回答正确性进行筛选；多模态支持样本可包含图像输入作为上下文，但推理向量仍从语言侧答案表征计算。",
      "finding_ids": [
       "C-UE-01"
      ]
     },
     {
      "action_id": "R3-UE-01-002",
      "target_path": "data_and_interfaces",
      "before": "推理向量存储对象至少包括任务标识、来源模型标识、支持源标识、层标识、向量张量、向量维度、聚合样本数及提取配置。",
      "after": "推理向量相关数据用于记录逐语言层得到的任务级推理向量r_l及其层对应关系，并可结合向量来源和支持集来源区分LLM-derived、VLM-derived或VLM-MM等来源设置。",
      "finding_ids": [
       "C-UE-01"
      ]
     },
     {
      "action_id": "R3-UE-01-003",
      "target_path": "data_and_interfaces",
      "before": "选层结果对象至少包括目标模型标识、基准标识、向量来源、适配方式、候选层及选定层。",
      "after": "选层结果用于记录在留出开发子集上逐候选语言层评测后确定的选定注入层；不同向量来源和适配设置采用相同选层协议。",
      "finding_ids": [
       "C-UE-01"
      ]
     },
     {
      "action_id": "R3-UE-01-004",
      "target_path": "data_and_interfaces",
      "before": "评测存储对象包括样本标识、预测答案、标准答案、正确性、模型配置、向量来源、注入层和随机种子，以支持配对bootstrap分析。",
      "after": "评测数据用于记录生成结果、解析答案和逐样本正确性，并在相同评测划分下基于逐样本正确性对执行配对bootstrap分析；评测过程采用论文披露的相同提示、解码配置、答案解析器和随机种子设置。",
      "finding_ids": [
       "C-UE-01"
      ]
     }
    ]
   },
   {
    "round_number": 3,
    "check_id": "EN-03",
    "outcome": "blocked",
    "reason": "本次检查项指出存在19项原始材料未充分披露的技术细节，且finding仅明示了其中部分事项并概括为“另有15项”。在当前证据中，无法确认全部19项缺口的具体内容，也无法据此对inventor_confirmation_items作出完整、精确且不引入未证实技术事实的补充。为避免猜测实现细节或遗漏已识别缺口，本项需发明人或前序生成器补充完整缺口清单后再改稿。",
    "allowed_target_paths": [
     "inventor_confirmation_items"
    ],
    "requested_materials": [
     "请提供Generator已识别的19项原始材料未充分披露技术细节的完整逐项清单，包括每项对应的原始依据、涉及模块或步骤、缺失原因及建议确认问题。",
     "请发明人逐项确认目标VLM与基础LLM在层数、隐藏维度、分词器不一致时是否允许实施；如允许，请提供层映射、维度投影、token对齐或重分词的具体实现材料。",
     "请发明人逐项确认隐藏状态注入的实际作用范围，包括自回归时间步、语言token范围、答案token范围、提示预填充阶段及多层同时注入规则，并提供实现或实验记录。",
     "请发明人补充其余未明示缺口对应的实现说明、代码片段、实验配置、参数表或可复现实验记录；若某些方案未实际实现，请明确其仅作为待验证方案或删除依据。"
    ],
    "evidence_ids": [],
    "changes": []
   },
   {
    "round_number": 3,
    "check_id": "EN-04",
    "outcome": "blocked",
    "reason": "现有证据只能支持Reasoner/Solver双路径、最终答案标记隐藏状态差分、逐层平均、推理阶段在所选语言模型层自回归解码中加法注入，以及可学习适配的部分训练超参数。EN-04指出的关键可重复实施缺口中，答案区间程序化识别和异常对齐规则、主隐藏状态注入在Transformer块内的精确挂接点及prefill/decode覆盖范围、z_l^R/z_l^S定义、λ_rec具体数值、候选层范围、最终选定层编号和并列处理规则，均不能从本次证据中可靠补足。若直接改写会引入证据不存在的技术事实，因此本检查项不能安全修改。",
    "allowed_target_paths": [
     "implementation_boundaries"
    ],
    "requested_materials": [
     "请提供答案区间的程序化识别规则，包括最终答案A在C_R=(Q,T,A)与C_S=(Q,A)中的起止定位方法。",
     "请提供多标记答案在两条路径中的对齐算法，以及分词不一致、答案长度不一致、特殊标记或包装标记存在时的处理规则。",
     "请确认主隐藏状态注入在Transformer块内的精确挂接点，例如块输入、注意力残差后、MLP残差后或块输出。",
     "请确认主隐藏状态注入覆盖的生成阶段和标记范围，包括是否作用于提示prefill阶段、首个生成标记及全部后续decode语言标记。",
     "请提供可学习适配中z_l^R与z_l^S的完整定义、损失计算位置及与注入向量θ_l的关系。",
     "请提供λ_rec的具体数值；如使用固定为1或等效省略，也请明确说明。",
     "请确认可学习适配的停止条件是否仅为训练6个epoch，或是否还包含开发集早停、收敛阈值、最佳检查点选择等规则。",
     "请提供各基准的候选层范围、逐基准最终选定层编号、选层性能指标，以及多个候选层性能并列时的选择规则。"
    ],
    "evidence_ids": [
     "E0073",
     "E0074",
     "E0075",
     "E0081",
     "E0083",
     "E0098",
     "E0099",
     "E0100",
     "E0115",
     "E0118",
     "E0912",
     "E0913",
     "E0915",
     "E0932"
    ],
    "changes": []
   },
   {
    "round_number": 3,
    "check_id": "WR-03",
    "outcome": "modified",
    "reason": "仅需消除图1描述中的不确定用语“可能”。现有证据已明确表述为多模态对齐会改变语言侧推理方向，因此可在不引入新技术事实的前提下直接改写。",
    "allowed_target_paths": [
     "drawing_descriptions"
    ],
    "requested_materials": [],
    "evidence_ids": [
     "E0938",
     "E0005"
    ],
    "changes": [
     {
      "action_id": "R3-WR-03-001",
      "target_path": "drawing_descriptions",
      "before": "图1为LIFT动机示意图，示出多模态对齐可能改变视觉语言模型中的语言侧推理方向，以及来自基础语言模型的推理向量可作为对齐后视觉语言模型中的轻量干预方向。",
      "after": "图1为LIFT动机示意图，示出多模态对齐会改变视觉语言模型中的语言侧推理方向，以及来自基础语言模型的推理向量可作为对齐后视觉语言模型中的轻量干预方向。",
      "finding_ids": [
       "F-AMBIGUOUS_DRAWING_DESCRIPTIONS"
      ]
     }
    ]
   },
   {
    "round_number": 3,
    "check_id": "AI-02",
    "outcome": "blocked",
    "reason": "本次仅允许修改 inventor_confirmation_items。现有可编辑内容已经将 AI-02 所缺的关键训练/推理边界列为发明人确认事项，包括Transformer块内挂接点、自回归时间步和标记范围、以及基础LLM与目标VLM在分词器、层数、隐藏维度上的对应关系。现有证据仅支持语言侧、语言骨干、推理时自回归解码、冻结VLM骨干和视觉编码器、不更新VLM参数等边界，不能支持直接补写精确hook位置、prefill/decode覆盖规则或异构模型映射/投影实现；若强行补充会引入证据中不存在的技术事实。因此不能通过本轮局部改稿实质解决 AI-02，只能请求发明人补充材料。",
    "allowed_target_paths": [
     "inventor_confirmation_items"
    ],
    "requested_materials": [
     "请发明人确认主隐藏状态注入在每个Transformer块内的精确挂接点，例如块输入、注意力子层输出/残差后、MLP子层输出/残差后或块输出，并说明对应到Qwen2.5-VL-7B-Instruct和InternVL2.5-8B代码模块的hook名称或张量位置。",
     "请发明人确认推理时加法注入覆盖的自回归阶段和token范围：是否作用于prompt prefill阶段、首个生成token、全部后续生成语言token；是否排除视觉token、图像占位token、系统/用户提示token或特殊token。",
     "请发明人确认基础语言模型与目标视觉语言模型之间的对应要求：是否必须共享或兼容分词器、语言层数、层编号、隐藏维度和语言骨干结构；若允许不一致，请提供层映射规则和隐藏维度投影/适配实现。",
     "请发明人提供静态注入与可学习适配各自的参数更新边界清单，包括冻结模块、可训练向量参数、是否涉及跨模态投影模块、语言骨干、视觉编码器或其他适配器参数。",
     "请发明人提供部署/推理接口层面的实现说明或伪代码，至少包括目标层选择后的hook注册位置、输入输出张量形状、注入向量广播方式以及仅修改语言token隐藏状态的过滤规则。"
    ],
    "evidence_ids": [
     "E0002",
     "E0093",
     "E0095",
     "E0101",
     "E0118",
     "E0122",
     "E0259"
    ],
    "changes": []
   },
   {
    "round_number": 3,
    "check_id": "AI-03",
    "outcome": "blocked",
    "reason": "当前证据仅支持答案标记隐藏状态差分、逐层任务级推理向量、静态/可学习注入公式、对齐损失公式以及可学习适配训练超参数；但未给出z_l^R和z_l^S的张量来源、token位置、维度和计算方式，未给出λ_rec的具体取值或选择规则，未给出答案span程序化识别及两路径分词/标记对齐异常处理规则，也未给出主隐藏状态注入在Transformer块内的精确hook位置。上述内容属于算法特征可实施性的关键细节，无法在不引入证据外技术事实的情况下补全，因此本检查项不能安全改稿。",
    "allowed_target_paths": [
     "detailed_steps"
    ],
    "requested_materials": [
     "请发明人提供可学习适配中z_l^R和z_l^S的完整定义，包括其来源路径、模型层、token位置或聚合区间、张量维度以及由隐藏状态或注入后激活计算得到的具体方式。",
     "请发明人提供λ_rec的具体数值；如不是固定值，请提供其选择规则、搜索范围、选择数据集或开发集依据。",
     "请发明人提供最终答案span的程序化识别规则，包括boxed答案、选择项、是非答案、数值答案等不同答案格式的定位方式。",
     "请发明人提供多标记答案在Reasoner路径C_R与Solver路径C_S之间的对齐算法，以及两条路径分词结果不一致、答案长度不一致、特殊标记出现或答案span无法唯一识别时的异常处理规则。",
     "请发明人确认主隐藏状态注入在Transformer块中的精确hook位置，是块输入、注意力残差后、MLP残差后、块输出，还是模型实现中的其他等效位置，并说明该hook对应的张量形状。"
    ],
    "evidence_ids": [
     "E0075",
     "E0076",
     "E0081",
     "E0083",
     "E0097",
     "E0102",
     "E0912",
     "E0913",
     "E0915",
     "E0916",
     "E0922",
     "E0923",
     "E0932"
    ],
    "changes": []
   }
  ],
  "unresolved_check_ids": [
   "UE-01",
   "EN-03",
   "EN-04",
   "CS-03",
   "AI-02",
   "AI-03"
  ]
 },
 "figures_status": {
  "figure_plan": [
   "图1：系统边界与总体架构图。展示离线支持集、Reasoner-Solver双路径教师强制前向、答案token隐藏状态差分、层级Reasoning Vector集合、保留开发集选层、静态注入/可学习适配、目标VLM输出答案与准确率。对应论文图：fig:method；证据：E0939。",
   "图2：Reasoning Vector计算流程图。展示C_R=(Q,T,A)与C_S=(Q,A)在同一来源模型中前向，最终答案token对齐读取，按δ_l(a)差分并按token与样本平均得到r_l。证据：E0073、E0074、E0075、E0912、E0913。",
   "图3：语言侧注入结构图。展示向量仅注入目标VLM语言骨干选定层，视觉编码器不修改；静态路径使用r_l，可学习路径使用θ_l。证据：E0065、E0093、E0914、E0939。",
   "图4：层选择流程图。展示每个候选语言层在100个训练样本保留开发子集上单独评测，选择最佳层后用于完整评测；评测样本不用于选层。证据：E0114、E0139、E0413。",
   "图5：实验结果柱状/表格附图。展示Qwen2.5-VL和InternVL2.5在Baseline、LLM-derived、VLM-derived、LLM-learnable、VLM-learnable下的六基准准确率和平均准确率。证据：E0924、E0925。",
   "图6：跨层相似性热力图。展示LLM-derived与VLM-derived向量在GSM8K上的跨层余弦相似度，用于说明层级组织关系。对应论文图：fig:cos。证据：E0941。",
   "图7：层敏感性曲线图。展示LLM-derived与VLM-derived在不同注入层上的六数据集平均性能，用于说明注入效果强烈依赖层选择。对应论文图：fig:layerwise。证据：E0942、E0250。",
   "图8：注意力头输出注入扩展图。展示head-wise向量v_Attn^(l,m)的计算和推理时对o^(l,m)(t)的加法注入。证据：E0410、E0413、E0421、E0937。",
   "图9：案例修复对比图。展示Baseline、VLM-derived、LLM-derived在代表性推理题上的中间推理路径和最终答案差异。对应论文图：fig:case。证据：E0181、E0940。"
  ],
  "generator_drawings": [
   "图1为系统总体架构图，展示离线支持集、Reasoner-Solver双路径教师强制前向、答案token隐藏状态差分、层级Reasoning Vector集合、保留开发集选层、静态注入或可学习适配、目标VLM输出答案与准确率。",
   "图2为Reasoning Vector计算流程图，展示C_R=(Q,T,A)与C_S=(Q,A)在同一来源模型中前向，最终答案token对齐读取，按δ_l(a)差分并按token与样本平均得到r_l。",
   "图3为语言侧注入结构图，展示向量仅注入目标VLM语言骨干选定层，视觉编码器不修改；静态路径使用r_l，可学习路径使用θ_l。",
   "图4为层选择流程图，展示每个候选语言层在100个训练样本保留开发子集上单独评测，选择最佳层后用于完整评测；评测样本不用于选层。",
   "图5为实验结果图，展示Qwen2.5-VL和InternVL2.5在Baseline、LLM-derived、VLM-derived、LLM-learnable、VLM-learnable下的六基准准确率和平均准确率。",
   "图6为跨层相似性热力图，展示LLM-derived与VLM-derived向量在GSM8K上的跨层余弦相似度，用于说明层级组织关系。",
   "图7为层敏感性曲线图，展示LLM-derived与VLM-derived在不同注入层上的六数据集平均性能，用于说明注入效果依赖层选择。",
   "图8为注意力头输出注入扩展图，展示head-wise向量v_Attn^(l,m)的计算和推理时对o^(l,m)(t)的加法注入。",
   "图9为案例修复对比图，展示Baseline、VLM-derived、LLM-derived在代表性推理题上的中间推理路径和最终答案差异。"
  ],
  "drawing_descriptions": [
   "图1为LIFT动机示意图，示出多模态对齐会改变视觉语言模型中的语言侧推理方向，以及来自基础语言模型的推理向量可作为对齐后视觉语言模型中的轻量干预方向。",
   "图2为LIFT方法概览图，示出各层中Reasoner路径与Solver路径的隐藏状态差分及平均以获得Reasoning Vector、可学习适配仅优化注入向量并冻结视觉语言模型骨干，以及推理时向选定视觉语言模型层注入向量。",
   "图3为代表性推理修复案例图。",
   "图4为GSM8K上基础语言模型来源向量与视觉语言模型来源向量的跨层余弦相似度图。",
   "图5为基础语言模型来源向量与视觉语言模型来源向量在六个数据集上平均的逐层性能图。"
  ],
  "generator_docx_media": 5,
  "reviewer_docx_media": 0,
  "paper_figure_count": 5
 }
};
